services:
  redis:
    image: redis:7-alpine
    container_name: mrs-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mrs-mqtt
    ports:
      - "1883:1883"
    volumes:
      - ./infra/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    restart: unless-stopped
